AllCops:
  Exclude:
    - 'dev_test/**'
    - 'lib/hoalife/concern.rb' # copied from rails source

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Metrics/ClassLength:
  Exclude:
    - 'test/**/*_test.rb'

Metrics/MethodLength:
  Exclude:
    - 'test/**/*_test.rb'
